# Estágio de Runtime: Usa o Java 21 (versão leve Alpine)
FROM eclipse-temurin:21-jdk-alpine

# Define o diretório de trabalho dentro do contentor
WORKDIR /app

# Copia o ficheiro .jar gerado pelo Maven para o contentor
# O asterisco garante que ele apanha o jar mesmo que o nome mude ligeiramente
COPY target/*.jar app.jar

# Expõe a porta (opcional no Dockerfile, mas boa prática)
# O Docker Compose tratará do mapeamento real
EXPOSE 8080

# Comando para iniciar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]